############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Qualification"
url = "experience/"
weight = 2

[[main]]
name = "Projects"
url = "projects/"
weight = 3

[[main]]
name = "Cheatsheets"
url = "cheatsheets/"
weight = 4

[[main]]
weight = 5
name = "Blogs"
hasChildren = true

[[main]]
parent = "Blogs"
name = "Authors"
url = "authors/"


[[main]]
parent = "Blogs"
name = "Categories"
url = "categories/"

[[main]]
parent = "Blogs"
name = "Recent Blogs"
url = "blog/"


# footer menu
[[footer]]
name = "Recent Blogs"
url = "blog/"
weight = 1

[[footer]]
name = "Cheatsheets"
url = "cheatsheets/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3
