############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Qualification"
url = "experience/"
weight = 2

[[main]]
name = "Cheatsheets"
url = "cheatsheets/"
weight = 3

[[main]]
name = "Checklists"
url = "checklists/"
weight = 4

[[main]]
name = "Projects"
url = "projects/"
weight = 5

[[main]]
weight = 6
name = "Blogs"
hasChildren = true

[[main]]
parent = "Blogs"
name = "Recent Blogs"
url = "blog/"
weight = 1

[[main]]
parent = "Blogs"
name = "Authors"
url = "authors/"


[[main]]
parent = "Blogs"
name = "Categories"
url = "categories/"

[[main]]
parent = "Blogs"
name = "Tags"
url = "tags/"

# footer menu
[[footer]]
name = "My Setup"
url = "projects/setup"
weight = 1

[[footer]]
name = "Recent Blogs"
url = "blog/"
weight = 2

[[footer]]
name = "Cheatsheets"
url = "cheatsheets/"
weight = 3

[[footer]]
name = "Checklists"
url = "checklists/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5
